name: R2 to R2 Migration
type = s3
provider = Cloudflare R2
access_key_id = ${DST_AK}
secret_access_key = ${DST_SK}
endpoint = ${DST_ENDPOINT}
region = auto
EOF
echo "rclone.conf generated at $RCLONE_CONFIG_DIR"


- name: Show bucket/prefix info
run: |
echo "SRC: ${SRC_ENDPOINT}/${SRC_BUCKET}"
echo "DST: ${DST_ENDPOINT}/${DST_BUCKET}"
echo "PREFIX: '${{ matrix.prefix }}'"


- name: Migrate prefix
timeout-minutes: 1440 # 24h 上限，必要时可提高（GitHub 每 job 最长 6h~72h 取决于计划）
run: |
set -euo pipefail
export RCLONE_CONFIG=$RCLONE_CONFIG_DIR/rclone.conf


MODE="${{ github.event.inputs.mode || 'copy' }}"
SRC="srcr2:${SRC_BUCKET}/${{ matrix.prefix }}"
DST="dstr2:${DST_BUCKET}/${{ matrix.prefix }}"


# 调优参数：根据并发与对象大小可调整
COMMON_FLAGS=(
--s3-chunk-size 64M
--s3-upload-concurrency 16
--transfers 32
--checkers 64
--multi-thread-streams 8
--fast-list
--use-server-modtime
--retries 10
--low-level-retries 20
--retries-sleep 10s
--stats 30s
--stats-one-line
--progress
)


if [ "$MODE" = "sync" ]; then
echo "Running rclone sync (mirror)..."
rclone sync "$SRC" "$DST" "${COMMON_FLAGS[@]}"
else
echo "Running rclone copy (incremental)..."
rclone copy "$SRC" "$DST" "${COMMON_FLAGS[@]}"
fi


- name: Verify prefix sizes
if: always()
run: |
export RCLONE_CONFIG=$RCLONE_CONFIG_DIR/rclone.conf
SRC="srcr2:${SRC_BUCKET}/${{ matrix.prefix }}"
DST="dstr2:${DST_BUCKET}/${{ matrix.prefix }}"
echo "Checking sizes for $SRC vs $DST"
rclone size "$SRC" || true
rclone size "$DST" || true
